// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSxIV-9Hz-E5aNPeSPeSOQaIZTGEmqaXQ',
    appId: '1:202838828206:web:aac0a094947630d006f93f',
    messagingSenderId: '202838828206',
    projectId: 'the-wall-app-b7d3d',
    authDomain: 'the-wall-app-b7d3d.firebaseapp.com',
    storageBucket: 'the-wall-app-b7d3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2MnSa5rhJaw76D9dQYslXDON5tPxElwA',
    appId: '1:202838828206:android:588dbf1f8d2759f806f93f',
    messagingSenderId: '202838828206',
    projectId: 'the-wall-app-b7d3d',
    storageBucket: 'the-wall-app-b7d3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_oCamwRMA0s9SUdPDIcRqOt4P0Por1ok',
    appId: '1:202838828206:ios:dfc5920f1a30c18006f93f',
    messagingSenderId: '202838828206',
    projectId: 'the-wall-app-b7d3d',
    storageBucket: 'the-wall-app-b7d3d.appspot.com',
    iosClientId: '202838828206-eto405igftce91migeec628null70998.apps.googleusercontent.com',
    iosBundleId: 'com.example.theWallApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_oCamwRMA0s9SUdPDIcRqOt4P0Por1ok',
    appId: '1:202838828206:ios:158b0c028e5f1c2706f93f',
    messagingSenderId: '202838828206',
    projectId: 'the-wall-app-b7d3d',
    storageBucket: 'the-wall-app-b7d3d.appspot.com',
    iosClientId: '202838828206-pvkbiuup2c6igkpf2ll8oufluqkib7ha.apps.googleusercontent.com',
    iosBundleId: 'com.example.theWallApp.RunnerTests',
  );
}
